services:
  webserver: # This service is now PHP-FPM
    build:
      context: ./assets/php-fpm # Path to the directory containing your Dockerfile
      args:
        PHP_VERSION: ${MOODLE_DOCKER_PHP_VERSION:-8.2} # Default to 8.2 if not set
    # image: "php:${MOODLE_DOCKER_PHP_VERSION}-fpm" # This line is replaced by the build context above
    # NOTE: The Dockerfile at ./assets/php-fpm/Dockerfile should handle PHP extensions.
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/moodle-docker/moodle_html"  # Moodle code, path matches Nginx root
      # MOODLE_DOCKER_DATAROOT must be set by the user.
      # This path is where PHP will access moodledata directly.
      - "${MOODLE_DOCKER_DATAROOT}:/var/www/moodle-docker/moodle_data"
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}" # Used for $CFG->wwwroot
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT}" # Add this line
      # MOODLE_DOCKER_TIMEOUT_FACTOR is kept as it might be used by Behat CLI tests
      MOODLE_DOCKER_TIMEOUT_FACTOR: "${MOODLE_DOCKER_TIMEOUT_FACTOR}"

  nginx:
    image: "nginx:latest"
    depends_on:
      - webserver # Depends on the PHP-FPM service
      - mailpit   # Depends on the Mailpit service for proxying
    volumes:
      # Nginx root directive points to /var/www/moodle-docker/moodle_html
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/moodle-docker/moodle_html:ro"
      # Nginx alias for /dataroot/ points to /var/www/moodle-docker/moodle_data
      - "${MOODLE_DOCKER_DATAROOT}:/var/www/moodle-docker/moodle_data:ro"
      - "${ASSETDIR}/nginx/moodle.conf:/etc/nginx/conf.d/default.conf:ro"
      # Note: Port mapping will be handled by webserver.port.yml
      # Note: Behat faildump volume will be handled by behat-faildump.yml
    environment:
      MOODLE_DOCKER_RUNNING: 1 # May not be strictly needed by Nginx but consistent
